### ISSUE TITLE
Addnode

### ISSUE THREAD

**Issue by TylerAnder** [osmanlialtincoin-project/osmanlialtincoin#1]
Hi, is there any addnode to connect to the network? ty

**Comment by osmanlialtincoin-project** [comment]
hi, the blockchain is currently being updated. The website is also under
construction. Furthermore, a mining pool is being worked on. All in all,
the project will become active in 1-2 months. The blockchain will contain
at least 3 seed nodes. Please be patient. It will be worth it.

Tyler Anderson ***@***.***> schrieb am Sa. 24. Sept. 2022 um
06:44:

**Comment by TylerAnder** [comment]
Hi, okk thank you for the updates, will be waiting then.
