### ISSUE TITLE
nodes

### ISSUE THREAD

**Issue by grand96** [osmanlialtincoin-project/osmanlialtincoin#1]
Hi! Node 31.18.8.26:2333 not work. Need any nodes and blockexplorer.

**Comment by osmanlialtincoin-project** [comment]
Hello,
try this here 91.66.82.5.2333
the DNS seeders are still a work in progress, so work with them first.


grand96 ***@***.***> schrieb am Mo. 27. Juni 2022 um 07:56:

**Comment by grand96** [comment]
91.66.82.5.2333 - not connect

**Comment by osmanlialtincoin-project** [comment]
looks like it's working now

grand96 ***@***.***> schrieb am Mo. 27. Juni 2022 um 08:19:

**Comment by grand96** [comment]
Yes! Work!
